FROM python:3.9-slim

# Defining the author
LABEL author="matilde.lopestelmocaladosanches@ugent.be"
LABEL maintainer="Lotte.Pohl@UGent.be"

# Set working directory
WORKDIR /TRAINING_MODEL

# Install the Python dependencies
RUN pip install \
    Flask>=2.2.2 \
    scikit-learn==1.3.1 \
    joblib==1.3.2 \
    numpy==1.23.5

# Copy the training script to the working directory
COPY ../train.py .

# Run the training script that generates the model
CMD ["python", "train.py"]

## COMMAND USED TO RUN THE CONTAINER AND SAVE THE MODEL IN TRAINING_MODEL (from the cloned repository):
## docker run --rm -v ./TRAINING_MODEL:/app/models train_image 